async function loadTopicOptions(){const select=document.getElementById("topicFilter");if(!select)return;const section=activeSection;try{const topics=await apiGetQuestionTopics(section);select.innerHTML="<option value=\"\">All topics</option>"+topics.map(topic=>{const option=document.createElement("option");option.value=topic;option.textContent=topic;return option.outerHTML}).join("")}catch(_){select.innerHTML="<option value=\"\">All topics</option>"}}
// COCPrep — reusable exam runner for Section A (MCQ) and Section B (True / False)
const FREE_LIMIT = 20; // Free access policy; never used to cap a Premium session.
const el = Object.fromEntries(["questionCard","loadingCard","paywallCard","emptyCard","errorCard","questionCondition","questionText","choicesList","submitAnswerBtn","feedback","feedbackBadge","feedbackExplanation","nextQuestionBtn","prevQuestionBtn","progressCount","progressBar","questionNav","questionMeta","flagBtn","timer","submitExamBtn","errorBody","retryBtn","paywallNote","paywallPending","paywallPaymentForm","mpesaCodeInput","submitPaymentBtn","paymentStatus","refreshEntitlementBtn"].map(id=>[id,document.getElementById(id)]));
let currentQuestion=null, selectedChoiceKey=null, selectedTrueFalse={}, activeSection="mcq", mode="practice", questionIndex=0, answered=[], flagged=new Set(), sessionQuestions=[], timerId=null, seconds=1800;
const reportReasons=[["wrong_answer","Wrong answer"],["unclear","Question is unclear"],["typo","Typographical error"],["multiple_correct","More than one correct answer"],["no_correct","No correct answer"],["medical_information","Incorrect medical information"],["incomplete","Missing information"],["image_problem","Image / diagram problem"],["other","Other"]];

function showState(name){["questionCard","loadingCard","paywallCard","emptyCard","errorCard"].forEach(k=>el[k].hidden=k!==name)}
function isGroupedTrueFalse(q){return q?.question_type==="truefalse_group"||Array.isArray(q?.statements)}
function normalizeChoices(q){const raw=q.choices||[];if(isGroupedTrueFalse(q))return (q.statements||raw).map((c,i)=>({key:String(c.key||String.fromCharCode(65+i)),text:String(c.text||c.statement||""),questionId:c.question_id||c.id}));const isTF=q.question_type==="truefalse"||q.section==="truefalse";if(Array.isArray(raw)&&raw[0]?.key)return raw.map(c=>({key:String(c.key),text:String(c.text)}));if(Array.isArray(raw))return raw.map((text,i)=>({key:isTF?(i===0?"TRUE":"FALSE"):String.fromCharCode(65+i),text:String(text)}));return Object.entries(raw).map(([key,text])=>({key,text:String(text)}))}
function renderNavigator(){el.questionNav.innerHTML="";const total=Math.max(Number(currentQuestion?.total_questions||currentQuestion?.totalQuestions||sessionQuestions.length||questionIndex+1),questionIndex+1);for(let i=0;i<Math.min(total,sessionQuestions.length);i++){const b=document.createElement("button");b.className="question-number";b.textContent=i+1;if(i===questionIndex)b.classList.add("is-current");if(answered[i])b.classList.add("is-answered");if(flagged.has(i))b.classList.add("is-flagged");b.setAttribute("aria-label",`Go to question ${i+1}`);b.onclick=()=>{if(sessionQuestions[i]){questionIndex=i;renderQuestion(sessionQuestions[i])}};el.questionNav.appendChild(b)}const knownTotal=currentQuestion?.total_questions||currentQuestion?.totalQuestions||sessionQuestions.length||"—";el.progressCount.textContent=`${questionIndex+1} / ${knownTotal}`;el.progressBar.style.width=knownTotal==="—"?"0%":`${Math.round(((questionIndex+1)/knownTotal)*100)}%`;el.questionMeta.textContent=`Question ${questionIndex+1} of ${knownTotal}`}
function renderQuestion(q){const isTF=activeSection==="truefalse";const valid=isTF?(q.section==="truefalse"||q.question_type?.startsWith("truefalse")||Array.isArray(q.statements)):(q.section!=="truefalse"&&q.question_type!=="truefalse"&&q.question_type!=="truefalse_group");if(!valid){throw new Error(`The question service returned the wrong format for Section ${isTF?"B":"A"}.`)}currentQuestion=q;selectedChoiceKey=null;selectedTrueFalse={};el.questionCondition.textContent=q.condition||q.unit||"Clinical medicine";el.questionText.textContent=q.question_text;el.choicesList.innerHTML="";const groupedTF=isGroupedTrueFalse(q);if(groupedTF){const table=document.createElement("table");table.className="truefalse-table";table.style.cssText="width:100%;border-collapse:separate;border-spacing:0 10px;table-layout:fixed";table.innerHTML="<thead><tr><th scope=\"col\" style=\"width:12%;text-align:left;padding:8px\">Option</th><th scope=\"col\" style=\"width:58%;text-align:left;padding:8px\">Statement</th><th scope=\"col\" style=\"width:15%;text-align:center;padding:8px\">True</th><th scope=\"col\" style=\"width:15%;text-align:center;padding:8px\">False</th></tr></thead><tbody></tbody>";const tbody=table.querySelector("tbody");normalizeChoices(q).forEach(({key,text})=>{const row=document.createElement("tr");row.dataset.key=key;row.innerHTML=`<th scope="row" style="background:#f7faf9;border:1px solid #dce5e0;border-right:0;border-radius:12px 0 0 12px;padding:12px 8px;text-align:center">${key}</th><td class="choice-text" style="background:#f7faf9;border-top:1px solid #dce5e0;border-bottom:1px solid #dce5e0;padding:12px 8px"></td><td style="background:#f7faf9;border-top:1px solid #dce5e0;border-bottom:1px solid #dce5e0;text-align:center"><input type="radio" name="tf-${questionIndex}-${key}" value="TRUE" aria-label="${key} True"></td><td style="background:#f7faf9;border:1px solid #dce5e0;border-left:0;border-radius:0 12px 12px 0;text-align:center"><input type="radio" name="tf-${questionIndex}-${key}" value="FALSE" aria-label="${key} False"></td>`;row.querySelector(".choice-text").textContent=text;row.querySelectorAll("input").forEach(input=>input.onchange=()=>selectTrueFalse(key,input.value));tbody.appendChild(row)});el.choicesList.appendChild(table)}else normalizeChoices(q).forEach(({key,text})=>{const d=document.createElement("div");d.className="choice";d.dataset.key=key;d.innerHTML=`<span class="choice-letter">${activeSection==="truefalse"?(key==="TRUE"?"T":"F"):key}</span><span class="choice-text"></span>`;d.querySelector(".choice-text").textContent=text;d.onclick=()=>selectChoice(key);el.choicesList.appendChild(d)});el.feedback.hidden=true;el.nextQuestionBtn.hidden=true;el.submitAnswerBtn.hidden=false;el.submitAnswerBtn.textContent=groupedTF?"Check all answers":"Check answer";el.submitAnswerBtn.disabled=true;el.flagBtn.classList.toggle("is-flagged",flagged.has(questionIndex));renderNavigator();showState("questionCard")}
function selectChoice(key){if(!el.feedback.hidden)return;selectedChoiceKey=key;el.choicesList.querySelectorAll(".choice").forEach(c=>c.classList.toggle("is-selected",c.dataset.key===key));el.submitAnswerBtn.disabled=false}
function selectTrueFalse(key,answer){if(!el.feedback.hidden)return;selectedTrueFalse[key]=answer;const row=el.choicesList.querySelector(`[data-key="${key}"]`);row?.classList.add("has-answer");el.submitAnswerBtn.disabled=normalizeChoices(currentQuestion).some(choice=>!selectedTrueFalse[choice.key])}
async function loadNextQuestion(){showState("loadingCard");try{const result=await apiGetNextQuestion({section:activeSection,topic:document.getElementById("topicFilter")?.value.trim()||undefined});if(result.blocked){const premiumSection=activeSection==="truefalse";el.paywallCard?.classList.toggle("paywall-card-premium",premiumSection);if(el.paywallTitle)el.paywallTitle.textContent=premiumSection?"Unlock Section B to continue":"Your first 20 questions are on us.";if(el.paywallDescription)el.paywallDescription.textContent=premiumSection?"Section B is premium content. Pay KSH 100 once for unlimited access to almost 1,000 True / False questions.":"Unlock 700+ unique MCQs, almost 1,000 True / False questions, answers, explanations, related FAQs, and unlimited lifetime access.";el.paywallNote.textContent=premiumSection?"No free trial is available for Section B.":(result.reason==="free_pool_exhausted"?"The free question set ran out early — unlock the full bank to continue.":"");showState("paywallCard");await refreshPaywallState();return}if(!result.question){el.emptyTitle&&(el.emptyTitle.textContent="No questions available yet");showState("emptyCard");return}sessionQuestions[questionIndex]=result.question;renderQuestion(result.question)}catch(err){el.errorBody.textContent=err.message||"Couldn't reach the server.";showState("errorCard")}}
async function submitAnswer(){if(!currentQuestion)return;const groupedTF=isGroupedTrueFalse(currentQuestion);const choices=normalizeChoices(currentQuestion);if((groupedTF&&!choices.every(choice=>selectedTrueFalse[choice.key]))||(!groupedTF&&!selectedChoiceKey))return;el.submitAnswerBtn.disabled=true;el.submitAnswerBtn.textContent="Checking…";try{if(groupedTF){const results=[];for(const choice of choices){const result=await apiSubmitAnswer({questionId:choice.questionId,selectedChoice:selectedTrueFalse[choice.key],section:activeSection});results.push({...result,key:choice.key,selected:selectedTrueFalse[choice.key]});const row=el.choicesList.querySelector(`[data-key="${choice.key}"]`);row?.classList.add(result.correct?"is-correct-reveal":"is-wrong-reveal");const feedback=document.createElement("div");feedback.textContent=result.correct?`Correct — answer: ${result.correct_answer}`:`Incorrect — answer: ${result.correct_answer}`;feedback.style.cssText="font-size:12px;margin-top:5px;color:#0e8275";row?.querySelector(".choice-text")?.appendChild(feedback)}answered[questionIndex]={grouped:true,results,questionId:currentQuestion.id};const correctCount=results.filter(result=>result.correct).length;el.feedbackBadge.textContent=`${correctCount} of ${results.length} correct`;el.feedbackExplanation.textContent="Review each statement above. The correct answer is shown beside every option."}else{const result=await apiSubmitAnswer({questionId:currentQuestion.id,selectedChoice:selectedChoiceKey,section:activeSection});answered[questionIndex]={correct:result.correct,correct_answer:result.correct_answer,explanation:result.explanation,selected:selectedChoiceKey,questionId:currentQuestion.id};el.choicesList.querySelectorAll(".choice").forEach(c=>{if(c.dataset.key===result.correct_answer)c.classList.add("is-correct-reveal");else if(c.dataset.key===selectedChoiceKey&&!result.correct)c.classList.add("is-wrong-reveal")});el.feedbackBadge.textContent=result.correct?"Correct":"Not quite";el.feedbackExplanation.textContent=result.explanation||"Review the concept and try a similar question."}el.submitAnswerBtn.hidden=true;el.nextQuestionBtn.hidden=false;el.feedback.hidden=false;renderNavigator();saveProgress()}catch(err){el.submitAnswerBtn.disabled=false;el.submitAnswerBtn.textContent=groupedTF?"Check all answers":"Check answer";el.errorBody.textContent=err.message||"Couldn't submit your answer.";showState("errorCard")}}
function nextQuestion(){questionIndex++;if(sessionQuestions[questionIndex])renderQuestion(sessionQuestions[questionIndex]);else loadNextQuestion()}
function startExam(section="mcq"){activeSection=section==="truefalse"?"truefalse":"mcq";mode="practice";questionIndex=0;answered=[];flagged=new Set();sessionQuestions=[];currentQuestion=null;document.getElementById("practiceSectionTag").textContent=activeSection==="truefalse"?"SECTION B":"SECTION A";document.getElementById("practiceTitle").textContent=activeSection==="truefalse"?"True / False practice":"MCQ practice";el.timer.hidden=true;loadTopicOptions();loadNextQuestion()}
function saveProgress(){const safeQuestions=sessionQuestions.map(q=>q?{id:q.id,question_text:q.question_text,choices:q.choices,statements:q.statements,condition:q.condition,unit:q.unit,section:q.section,question_type:q.question_type}:null);localStorage.setItem("cocprep-progress",JSON.stringify({activeSection,questionIndex,answered,flagged:[...flagged],sessionQuestions:safeQuestions}))}
async function toggleFlag(){if(!currentQuestion)return;try{const r=await apiToggleQuestionFlag(currentQuestion.id);flagged.has(questionIndex)?flagged.delete(questionIndex):flagged.add(questionIndex);el.flagBtn.classList.toggle("is-flagged",flagged.has(questionIndex));el.flagBtn.querySelector("span").textContent=r.flagged?"Saved":"Flag";renderNavigator();saveProgress()}catch(e){el.flagBtn.querySelector("span").textContent=e.message}}
function openReport(){if(!currentQuestion)return;const box=document.createElement("div");box.id="cocReportModal";box.style.cssText="position:fixed;inset:0;background:#0d2b2acc;display:grid;place-items:center;padding:20px;z-index:20";box.innerHTML=`<section style="background:#fff;border-radius:18px;max-width:500px;width:100%;padding:28px;position:relative"><button id="closeCocReport" style="position:absolute;right:18px;top:12px;border:0;background:none;font-size:24px;color:#73817e">×</button><span class="eyebrow">Question quality</span><h2>Report a problem</h2><p style="color:#73817e">What's wrong with this question?</p><form id="cocReportForm"><div style="display:grid;gap:9px">${reportReasons.map(([v,l])=>`<label style="display:flex;gap:9px;align-items:center"><input type="radio" name="reason" value="${v}" required>${l}</label>`).join("")}</div><label class="field"><span class="field-label">Additional details <small>(optional)</small></span><textarea id="cocReportDetails" rows="4" placeholder="Tell us what you think is wrong..." style="width:100%;border:1px solid #dce5e0;border-radius:9px;padding:10px"></textarea></label><p id="cocReportStatus" style="color:#0e8275;font-size:13px"></p><button class="btn btn-primary btn-block" type="submit">Submit report</button></form></section>`;document.body.appendChild(box);document.getElementById("closeCocReport").onclick=()=>box.remove();document.getElementById("cocReportForm").onsubmit=async(e)=>{e.preventDefault();const reason=new FormData(e.currentTarget).get("reason"),status=document.getElementById("cocReportStatus"),button=e.currentTarget.querySelector("button[type=submit]");button.disabled=true;try{const r=await apiSubmitQuestionReport(currentQuestion.id,reason,document.getElementById("cocReportDetails").value);status.textContent=r.duplicate?"You've already reported this question.":"Report submitted — thank you. Our team will review this question.";if(r.duplicate)button.hidden=true}catch(err){status.textContent=err.message;button.disabled=false}}}
const reportButton=document.createElement("button");reportButton.className="flag-button";reportButton.innerHTML="⚠ <span>Report <em>Premium</em></span>";reportButton.onclick=openReport;el.flagBtn.parentNode.appendChild(reportButton);
async function refreshPaywallState(){if(await apiCheckEntitlement()){loadNextQuestion();return}const pending=await apiGetPendingPayment();el.paywallPending.hidden=!pending;el.paywallPaymentForm.hidden=!!pending}
document.getElementById("applyTopicFilterBtn")?.addEventListener("click",()=>startExam(activeSection));document.getElementById("topicFilter")?.addEventListener("keydown",e=>{if(e.key==="Enter"){e.preventDefault();startExam(activeSection)}});el.submitAnswerBtn.onclick=submitAnswer;el.nextQuestionBtn.onclick=nextQuestion;el.retryBtn.onclick=loadNextQuestion;el.prevQuestionBtn.onclick=()=>{if(questionIndex>0){questionIndex--;renderQuestion(sessionQuestions[questionIndex])}};el.flagBtn.onclick=toggleFlag;el.submitExamBtn.onclick=()=>{if(confirm("Finish this session and return to your progress?")){window.dispatchEvent(new CustomEvent("exam-finished"));showScreen("results")}};document.querySelectorAll("[data-mode]").forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll("[data-mode]").forEach(x=>x.classList.toggle("is-active",x===b));el.timer.hidden=mode!=="exam";if(mode==="exam")startTimer()});el.submitPaymentBtn.onclick=async()=>{const code=el.mpesaCodeInput.value.trim();if(!code){el.paymentStatus.textContent="Enter the M-Pesa confirmation code first.";el.paymentStatus.className="payment-status is-error";return}el.submitPaymentBtn.disabled=true;try{const r=await apiSubmitPaymentCode(code);el.paymentStatus.textContent=r.message||"Submitted for review.";el.paywallPending.hidden=false;el.paywallPaymentForm.hidden=true}catch(e){el.paymentStatus.textContent=e.message;el.paymentStatus.className="payment-status is-error"}finally{el.submitPaymentBtn.disabled=false}};el.refreshEntitlementBtn.onclick=refreshPaywallState;
function startTimer(){clearInterval(timerId);seconds=1800;timerId=setInterval(()=>{seconds--;el.timer.querySelector("b").textContent=`${String(Math.floor(seconds/60)).padStart(2,"0")}:${String(seconds%60).padStart(2,"0")}`;if(seconds<=0){clearInterval(timerId);alert("Time is up. Your session will be submitted.");showScreen("results")}},1000)}

let discussionPage = 0, discussionItems = [];
const baseRenderQuestion = renderQuestion;
renderQuestion = function (question) {
  baseRenderQuestion(question);
  renderDiscussion();
};
function discussionText(comment) { return comment.content || comment.body || ""; }
function renderDiscussion() {
  if (!currentQuestion || !el.questionCard) return;
  let panel = document.getElementById("questionDiscussion");
  if (!panel) {
    panel = document.createElement("section");
    panel.id = "questionDiscussion";
    panel.className = "discussion-panel";
    el.questionCard.insertBefore(panel, el.questionCard.querySelector(".question-actions"));
  }
  panel.innerHTML = `<div class="discussion-heading"><h3>💬 Discussion <span id="discussionCount"></span></h3><p>Community comments are for learning and are not official medical advice.</p></div><div id="discussionList" class="discussion-list"><p class="muted">Loading discussion…</p></div><button type="button" class="btn btn-secondary btn-sm" id="discussionMore" hidden>Load more</button><div id="discussionComposer"></div>`;
  discussionPage = 0; discussionItems = [];
  loadDiscussionPage();
}
async function loadDiscussionPage() {
  const list = document.getElementById("discussionList"), more = document.getElementById("discussionMore");
  if (!list || !currentQuestion) return;
  try {
    const rows = await apiGetQuestionComments(currentQuestion.id, discussionPage);
    discussionItems = discussionItems.concat(rows);
    document.getElementById("discussionCount").textContent = discussionItems.length ? `· ${discussionItems.length}${rows.length === 10 ? "+" : ""}` : "";
    list.innerHTML = "";
    const byParent = (parent) => discussionItems.filter((item) => (item.parent_comment_id || null) === parent);
    const draw = (items, depth = 0) => items.forEach((comment) => {
      const item = document.createElement("article");
      item.className = `discussion-comment depth-${Math.min(depth, 2)}`;
      item.innerHTML = `<div class="discussion-comment-meta"><strong>Student</strong><time>${formatRelativeTime(comment.created_at)}</time></div><p class="discussion-comment-body"></p><div class="discussion-comment-actions"><button type="button" data-action="like">👍 Like</button><button type="button" data-action="reply">Reply</button><button type="button" data-action="report">Report</button></div><div class="discussion-reply"></div>`;
      item.querySelector(".discussion-comment-body").textContent = discussionText(comment);
      item.querySelector('[data-action="like"]').onclick = async () => { try { await apiToggleCommentLike(comment.id); } catch (e) { alert(e.message); } };
      item.querySelector('[data-action="reply"]').onclick = () => {
        const reply = prompt("Write a helpful reply:");
        if (reply?.trim()) postDiscussionComment(reply.trim(), comment.id);
      };
      item.querySelector('[data-action="report"]').onclick = async () => {
        const reason = prompt("Why are you reporting this comment?");
        if (reason?.trim()) try { await apiReportComment(comment.id, reason.trim()); alert("Report submitted."); } catch (e) { alert(e.message); }
      };
      list.appendChild(item);
      draw(byParent(comment.id), depth + 1);
    });
    draw(byParent(null));
    more.hidden = rows.length < 10;
    more.onclick = () => { discussionPage += 1; loadDiscussionPage(); };
    renderDiscussionComposer();
  } catch (error) {
    list.innerHTML = `<p class="muted">${error.message || "Discussion unavailable."}</p>`;
    renderDiscussionComposer();
  }
}
async function renderDiscussionComposer() {
  const target = document.getElementById("discussionComposer");
  if (!target) return;
  const paid = await apiCheckEntitlement();
  target.innerHTML = paid
    ? `<form class="discussion-form"><textarea required maxlength="1000" rows="3" placeholder="Share your reasoning, ask a question, or add a useful memory tip…"></textarea><button class="btn btn-primary btn-sm" type="submit">Post comment</button></form>`
    : `<p class="discussion-locked">Premium access is required to post or reply. You can still read the discussion.</p>`;
  target.querySelector("form")?.addEventListener("submit", async (event) => {
    event.preventDefault();
    const textarea = event.currentTarget.querySelector("textarea");
    try { await postDiscussionComment(textarea.value.trim()); textarea.value = ""; } catch (error) { alert(error.message); }
  });
}
async function postDiscussionComment(content, parentId = null) {
  if (!content) return;
  await apiCreateQuestionComment(currentQuestion.id, content, parentId);
  discussionPage = 0; discussionItems = [];
  await loadDiscussionPage();
}