// COCPrep — reusable exam runner for Section A (MCQ) and Section B (True / False)
const FREE_LIMIT = 20;
const el = Object.fromEntries(["questionCard","loadingCard","paywallCard","emptyCard","errorCard","questionCondition","questionText","choicesList","submitAnswerBtn","feedback","feedbackBadge","feedbackExplanation","nextQuestionBtn","prevQuestionBtn","progressCount","progressBar","questionNav","questionMeta","flagBtn","timer","submitExamBtn","errorBody","retryBtn","paywallNote","paywallPending","paywallPaymentForm","mpesaCodeInput","submitPaymentBtn","paymentStatus","refreshEntitlementBtn"].map(id=>[id,document.getElementById(id)]));
let currentQuestion=null, selectedChoiceKey=null, activeSection="mcq", mode="practice", questionIndex=0, answered=[], flagged=new Set(), sessionQuestions=[], timerId=null, seconds=1800;
const reportReasons=[["wrong_answer","Wrong answer"],["unclear","Question is unclear"],["typo","Typographical error"],["multiple_correct","More than one correct answer"],["no_correct","No correct answer"],["medical_information","Incorrect medical information"],["incomplete","Missing information"],["image_problem","Image / diagram problem"],["other","Other"]];

function showState(name){["questionCard","loadingCard","paywallCard","emptyCard","errorCard"].forEach(k=>el[k].hidden=k!==name)}
function normalizeChoices(q){const raw=q.choices||[];if(Array.isArray(raw)&&raw[0]?.key)return raw.map(c=>({key:String(c.key),text:String(c.text)}));if(Array.isArray(raw))return raw.map((text,i)=>({key:i<2?["TRUE","FALSE"][i]:String.fromCharCode(65+i),text:String(text)}));return Object.entries(raw).map(([key,text])=>({key,text:String(text)}))}
function renderNavigator(){el.questionNav.innerHTML="";const total=Math.max(FREE_LIMIT,sessionQuestions.length||questionIndex+1);for(let i=0;i<total;i++){const b=document.createElement("button");b.className="question-number";b.textContent=i+1;if(i===questionIndex)b.classList.add("is-current");if(answered[i])b.classList.add("is-answered");if(flagged.has(i))b.classList.add("is-flagged");b.setAttribute("aria-label",`Go to question ${i+1}`);b.onclick=()=>{if(sessionQuestions[i]){questionIndex=i;renderQuestion(sessionQuestions[i])}};el.questionNav.appendChild(b)}el.progressCount.textContent=`${Math.min(questionIndex+1,total)} / ${total}`;el.progressBar.style.width=`${Math.round(((questionIndex+1)/total)*100)}%`;el.questionMeta.textContent=`Question ${questionIndex+1} of ${total}`}
function renderQuestion(q){currentQuestion=q;selectedChoiceKey=null;el.questionCondition.textContent=q.condition||q.unit||"Clinical medicine";el.questionText.textContent=q.question_text;el.choicesList.innerHTML="";normalizeChoices(q).forEach(({key,text})=>{const d=document.createElement("div");d.className="choice";d.dataset.key=key;d.innerHTML=`<span class="choice-letter">${activeSection==="truefalse"?(key==="TRUE"?"T":"F"):key}</span><span class="choice-text"></span>`;d.querySelector(".choice-text").textContent=text;d.onclick=()=>selectChoice(key);el.choicesList.appendChild(d)});el.feedback.hidden=true;el.submitAnswerBtn.hidden=false;el.nextQuestionBtn.hidden=true;el.submitAnswerBtn.disabled=true;el.flagBtn.classList.toggle("is-flagged",flagged.has(questionIndex));renderNavigator();showState("questionCard")}
function selectChoice(key){if(!el.feedback.hidden)return;selectedChoiceKey=key;el.choicesList.querySelectorAll(".choice").forEach(c=>c.classList.toggle("is-selected",c.dataset.key===key));el.submitAnswerBtn.disabled=false}
async function loadNextQuestion(){showState("loadingCard");try{const result=await apiGetNextQuestion({section:activeSection});if(result.blocked){el.paywallNote.textContent=result.reason==="free_pool_exhausted"?"The free question set ran out early — unlock the full bank to continue.":"";showState("paywallCard");await refreshPaywallState();return}if(!result.question){el.emptyTitle&&(el.emptyTitle.textContent="No questions available yet");showState("emptyCard");return}sessionQuestions[questionIndex]=result.question;renderQuestion(result.question)}catch(err){el.errorBody.textContent=err.message||"Couldn't reach the server.";showState("errorCard")}}
async function submitAnswer(){if(!selectedChoiceKey||!currentQuestion)return;el.submitAnswerBtn.disabled=true;el.submitAnswerBtn.textContent="Checking…";try{const result=await apiSubmitAnswer({questionId:currentQuestion.id,selectedChoice:selectedChoiceKey,section:activeSection});answered[questionIndex]={...result,selected:selectedChoiceKey,question:currentQuestion};el.choicesList.querySelectorAll(".choice").forEach(c=>{if(c.dataset.key===result.correct_answer)c.classList.add("is-correct-reveal");else if(c.dataset.key===selectedChoiceKey&&!result.correct)c.classList.add("is-wrong-reveal")});el.feedbackBadge.textContent=result.correct?"Correct":"Not quite";el.feedbackExplanation.textContent=result.explanation||"Review the concept and try a similar question.";el.submitAnswerBtn.hidden=true;el.nextQuestionBtn.hidden=false;el.feedback.hidden=false;renderNavigator();saveProgress()}catch(err){el.submitAnswerBtn.disabled=false;el.submitAnswerBtn.textContent="Check answer";el.errorBody.textContent=err.message||"Couldn't submit your answer.";showState("errorCard")}}
function nextQuestion(){questionIndex++;if(sessionQuestions[questionIndex])renderQuestion(sessionQuestions[questionIndex]);else loadNextQuestion()}
function startExam(section="mcq"){activeSection=section;mode="practice";questionIndex=0;answered=[];flagged=new Set();sessionQuestions=[];document.getElementById("practiceSectionTag").textContent=section==="truefalse"?"SECTION B":"SECTION A";document.getElementById("practiceTitle").textContent=section==="truefalse"?"True / False practice":"MCQ practice";el.timer.hidden=true;loadNextQuestion()}
function saveProgress(){localStorage.setItem("cocprep-progress",JSON.stringify({activeSection,questionIndex,answered,flagged:[...flagged],sessionQuestions}))}
async function toggleFlag(){if(!currentQuestion)return;try{const r=await apiToggleQuestionFlag(currentQuestion.id);flagged.has(questionIndex)?flagged.delete(questionIndex):flagged.add(questionIndex);el.flagBtn.classList.toggle("is-flagged",flagged.has(questionIndex));el.flagBtn.querySelector("span").textContent=r.flagged?"Saved":"Flag";renderNavigator();saveProgress()}catch(e){el.flagBtn.querySelector("span").textContent=e.message}}
function openReport(){if(!currentQuestion)return;const box=document.createElement("div");box.id="cocReportModal";box.style.cssText="position:fixed;inset:0;background:#0d2b2acc;display:grid;place-items:center;padding:20px;z-index:20";box.innerHTML=`<section style="background:#fff;border-radius:18px;max-width:500px;width:100%;padding:28px;position:relative"><button id="closeCocReport" style="position:absolute;right:18px;top:12px;border:0;background:none;font-size:24px;color:#73817e">×</button><span class="eyebrow">Question quality</span><h2>Report a problem</h2><p style="color:#73817e">What's wrong with this question?</p><form id="cocReportForm"><div style="display:grid;gap:9px">${reportReasons.map(([v,l])=>`<label style="display:flex;gap:9px;align-items:center"><input type="radio" name="reason" value="${v}" required>${l}</label>`).join("")}</div><label class="field"><span class="field-label">Additional details <small>(optional)</small></span><textarea id="cocReportDetails" rows="4" placeholder="Tell us what you think is wrong..." style="width:100%;border:1px solid #dce5e0;border-radius:9px;padding:10px"></textarea></label><p id="cocReportStatus" style="color:#0e8275;font-size:13px"></p><button class="btn btn-primary btn-block" type="submit">Submit report</button></form></section>`;document.body.appendChild(box);document.getElementById("closeCocReport").onclick=()=>box.remove();document.getElementById("cocReportForm").onsubmit=async(e)=>{e.preventDefault();const reason=new FormData(e.currentTarget).get("reason"),status=document.getElementById("cocReportStatus"),button=e.currentTarget.querySelector("button[type=submit]");button.disabled=true;try{const r=await apiSubmitQuestionReport(currentQuestion.id,reason,document.getElementById("cocReportDetails").value);status.textContent=r.duplicate?"You've already reported this question.":"Report submitted — thank you. Our team will review this question.";if(r.duplicate)button.hidden=true}catch(err){status.textContent=err.message;button.disabled=false}}}
const reportButton=document.createElement("button");reportButton.className="flag-button";reportButton.innerHTML="⚠ <span>Report <em>Premium</em></span>";reportButton.onclick=openReport;el.flagBtn.parentNode.appendChild(reportButton);
async function refreshPaywallState(){if(await apiCheckEntitlement()){loadNextQuestion();return}const pending=await apiGetPendingPayment();el.paywallPending.hidden=!pending;el.paywallPaymentForm.hidden=!!pending}
el.submitAnswerBtn.onclick=submitAnswer;el.nextQuestionBtn.onclick=nextQuestion;el.retryBtn.onclick=loadNextQuestion;el.prevQuestionBtn.onclick=()=>{if(questionIndex>0){questionIndex--;renderQuestion(sessionQuestions[questionIndex])}};el.flagBtn.onclick=toggleFlag;el.submitExamBtn.onclick=()=>{if(confirm("Finish this session and return to your progress?")){window.dispatchEvent(new CustomEvent("exam-finished"));showScreen("results")}};document.querySelectorAll("[data-mode]").forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll("[data-mode]").forEach(x=>x.classList.toggle("is-active",x===b));el.timer.hidden=mode!=="exam";if(mode==="exam")startTimer()});el.submitPaymentBtn.onclick=async()=>{const code=el.mpesaCodeInput.value.trim();if(!code){el.paymentStatus.textContent="Enter the M-Pesa confirmation code first.";el.paymentStatus.className="payment-status is-error";return}el.submitPaymentBtn.disabled=true;try{const r=await apiSubmitPaymentCode(code);el.paymentStatus.textContent=r.message||"Submitted for review.";el.paywallPending.hidden=false;el.paywallPaymentForm.hidden=true}catch(e){el.paymentStatus.textContent=e.message;el.paymentStatus.className="payment-status is-error"}finally{el.submitPaymentBtn.disabled=false}};el.refreshEntitlementBtn.onclick=refreshPaywallState;
function startTimer(){clearInterval(timerId);seconds=1800;timerId=setInterval(()=>{seconds--;el.timer.querySelector("b").textContent=`${String(Math.floor(seconds/60)).padStart(2,"0")}:${String(seconds%60).padStart(2,"0")}`;if(seconds<=0){clearInterval(timerId);alert("Time is up. Your session will be submitted.");showScreen("results")}},1000)}